[package]
name = "crux"
version = "0.1.0"
authors = ["Håkan Råberg <hakan.raberg@gmail.com>"]
license = "MIT"
edition = "2018"

[lib]
crate-type=["rlib", "cdylib"]

[dependencies]
croaring = "0.4"
edn = "0.3.0"
rdkafka = "0.21"
rocksdb = "0.12"
sha-1 = "0.8"
