# Check https://circleci.com/docs/2.0/language-clojure/ for more details
version: 2.1

executors:
  clojure:
    working_directory: ~/core2
    docker:
      - image: clojure:openjdk-11-tools-deps

jobs:
  setup:
    executor: clojure

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: 'md5sum deps.edn */deps.edn modules/*/deps.edn > .circleci-cache-key'

      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum ".circleci-cache-key" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-

      - run: 'clojure -Srepro -X:deps prep'
      - run: 'clojure -P'

      - persist_to_workspace:
          root: ~/
          paths:
            - .m2
            - .gitlibs
            - core2

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v4-dependencies-{{ checksum ".circleci-cache-key" }}

  test:
    executor: clojure

    steps:
      - attach_workspace:
          at: ~/

      - run: 'clojure -Srepro -X:test'

  integration-test:
    executor: clojure

    steps:
      - attach_workspace:
          at: ~/

      # TODO should test the other modules too
      - run: 'clojure -Srepro -X:integration-test'

workflows:
  build:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - integration-test:
          requires:
            - setup
