# Check https://circleci.com/docs/2.0/language-clojure/ for more details
version: 2.1

executors:
  clojure-lein:
    working_directory: ~/core2
    docker:
      - image: circleci/clojure:lein-2.9.5

jobs:
  setup:
    executor: clojure-lein

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: 'md5sum project.clj */project.clj modules/*/project.clj > .circleci-cache-key'

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum ".circleci-cache-key" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: './lein-sub install'
      - run: './lein-sub deps'

      - persist_to_workspace:
          root: ~/
          paths:
            - .m2
            - core2

  cache-m2:
    executor: clojure-lein

    steps:
      - attach_workspace:
          at: ~/

      - run: 'rm -rf ~/.m2/repository/com/xtdb/*'

      - save_cache:
          paths:
            - ~/.m2
          key: v2-dependencies-{{ checksum ".circleci-cache-key" }}

  test:
    executor: clojure-lein

    steps:
      - attach_workspace:
          at: ~/

      - run: './lein-sub check'
      - run: "./lein-sub test"

  integration-test:
    executor: clojure-lein

    steps:
      - attach_workspace:
          at: ~/

      # TODO should test the other modules too
      - run: "./lein-sub -s core test :integration"

workflows:
  build:
    jobs:
      - setup
      - cache-m2:
          requires:
            - setup
      - test:
          requires:
            - setup
      - integration-test:
          requires:
            - setup
