# Check https://circleci.com/docs/2.0/language-clojure/ for more details
version: 2.1

executors:
  clojure:
    working_directory: ~/core2
    docker:
      - image: clojure:openjdk-11-tools-deps

orbs:
  slack: circleci/slack@4.1

jobs:
  setup:
    executor: clojure

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # for Slack
      - run: apt-get update && apt-get install -y curl

      - run: 'md5sum deps.edn */deps.edn modules/*/deps.edn > .circleci-cache-key'

      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum ".circleci-cache-key" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-

      - run: 'clojure -Srepro -X:deps prep'

      # https://clojure.atlassian.net/browse/TDEPS-153
      # can remove `-Sthreads 1` when the Docker image updates to 1.11.0.1100 or later.
      - run: 'clojure -P -Sthreads 1'

      - persist_to_workspace:
          root: ~/
          paths:
            - .m2
            - .gitlibs
            - core2

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v4-dependencies-{{ checksum ".circleci-cache-key" }}

      - slack/notify:
          branch_pattern: master
          channel: xtdb-builds
          event: fail
          template: basic_fail_1

  test:
    executor: clojure

    steps:
      - attach_workspace:
          at: ~/

      - run: 'clojure -Srepro -X:test'

      - slack/notify:
          branch_pattern: master
          channel: xtdb-builds
          event: fail
          template: basic_fail_1

  integration-test:
    executor: clojure

    steps:
      - attach_workspace:
          at: ~/

      # TODO should test the other modules too
      - run: 'clojure -Srepro -X:integration-test'

      - slack/notify:
          branch_pattern: master
          channel: xtdb-builds
          event: fail
          template: basic_fail_1

  slt-test:
    executor: clojure
    resource_class: large

    steps:
      - attach_workspace:
          at: ~/

      - run: >-
          clojure -M -m core2.sql.logic-test.runner --verify --db xtdb
          test/core2/sql/logic_test/sqlite_test/select1.test
          test/core2/sql/logic_test/sqlite_test/select2.test
          test/core2/sql/logic_test/sqlite_test/select3.test
          test/core2/sql/logic_test/sqlite_test/select4.test
          test/core2/sql/logic_test/sqlite_test/random/expr/slt_good_0.test
          test/core2/sql/logic_test/sqlite_test/random/aggregates/slt_good_0.test
          test/core2/sql/logic_test/sqlite_test/random/groupby/slt_good_0.test
          test/core2/sql/logic_test/sqlite_test/random/select/slt_good_0.test

workflows:
  build:
    jobs:
      - setup:
          context: slack-bot
      - test:
          context: slack-bot
          requires:
            - setup
      - integration-test:
          context: slack-bot
          requires:
            - setup
      - slt-test:
          requires:
            - setup
